# https://doc.rust-lang.org/cargo/reference/manifest.html
[package]
name = "nix-zed-extensions"
version = "0.0.0"
edition = "2024"
rust-version = "1.95"
repository = "https://github.com/SwornSystems/nix-zed-extensions"
license = "GPL-3.0-or-later"
publish = false

# https://doc.rust-lang.org/rustc/lints/groups.html
[lints.rust]
unsafe_code = "forbid"

unused = { level = "deny", priority = -2 }
future-incompatible = { level = "deny", priority = -1 }
keyword-idents = { level = "deny", priority = -1 }
let-underscore = { level = "deny", priority = -1 }
nonstandard-style = { level = "deny", priority = -1 }
refining-impl-trait = { level = "deny", priority = -1 }
rust-2018-compatibility = { level = "deny", priority = -1 }
rust-2018-idioms = { level = "deny", priority = -1 }
rust-2021-compatibility = { level = "deny", priority = -1 }
rust-2024-compatibility = { level = "deny", priority = -1 }

# https://rust-lang.github.io/rust-clippy/master/index.html
[lints.clippy]
cargo = { level = "deny", priority = -1 }
complexity = { level = "deny", priority = -1 }
correctness = { level = "deny", priority = -1 }
nursery = { level = "deny", priority = -1 }
pedantic = { level = "deny", priority = -1 }
perf = { level = "deny", priority = -1 }
style = { level = "deny", priority = -1 }
suspicious = { level = "deny", priority = -1 }

# Personal Preferences
clone_on_ref_ptr = "deny"
cognitive_complexity = "allow"
module_name_repetitions = "allow"
option_if_let_else = "allow"
str_to_string = "deny"
too_many_lines = "allow"
multiple_crate_versions = "allow" # TODO: cargo-lock release

# TODO
missing_errors_doc = "allow"
missing_panics_doc = "allow"

[dependencies]
# Async
smol = "2.0"
smol-macros = "0.1"
futures-util = { version = "0.3", default-features = false, features = ["std"] }

# Cargo
cargo-lock = "11.1"

# WASM
wasmparser = { version = "0.258", default-features = false, features = [
  "component-model",
] }

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "1.1"

# Logging
tracing = { version = "0.1", default-features = false }
tracing-subscriber = { version = "0.3", default-features = false, features = [
  "std",
  "fmt",
  "ansi",
] }

# Errors
anyhow = "1.0"
