name: CI

on:
  workflow_dispatch:
  pull_request:

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

permissions: {}

jobs:
  setup:
    name: Setup
    permissions:
      contents: read # checkout
    strategy:
      matrix:
        runner:
          - ubuntu-24.04
          - ubuntu-24.04-arm
          - macos-26
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup
        uses: ./.github/actions/setup

  checks:
    name: Checks
    needs: setup
    runs-on: ubuntu-24.04
    permissions:
      contents: read # checkout
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup
        uses: ./.github/actions/setup
        with:
          rust: "true"

      - name: Run checks
        run: ./scripts/checks.nu

  test:
    name: Test
    needs: setup
    permissions:
      contents: read # checkout
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: ubuntu-24.04
            nixpkgs: github:NixOS/nixpkgs/nixos-26.05

          - runner: ubuntu-24.04
            nixpkgs: github:NixOS/nixpkgs/nixos-unstable

          - runner: ubuntu-24.04-arm
            nixpkgs: github:NixOS/nixpkgs/nixos-26.05

          - runner: ubuntu-24.04-arm
            nixpkgs: github:NixOS/nixpkgs/nixos-unstable

          - runner: macos-26
            nixpkgs: github:NixOS/nixpkgs/nixos-26.05

          - runner: macos-26
            nixpkgs: github:NixOS/nixpkgs/nixos-unstable
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup
        uses: ./.github/actions/setup

      - name: Test
        env:
          NIXPKGS: ${{ matrix.nixpkgs }}
        run: ./scripts/test.nu "${NIXPKGS}"
