name: Sync

on:
  workflow_dispatch:
  push:
    branches: [main]
  schedule:
    - cron: "0 3 * * *"

concurrency:
  group: sync
  cancel-in-progress: false

permissions: {}

jobs:
  sync:
    name: Sync
    runs-on: ubuntu-24.04
    permissions:
      actions: write # dispatch
      contents: write # push
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Setup
        uses: ./.github/actions/setup

      - name: Sync extensions
        run: nix run .#nix-zed-extensions -- sync

      - name: Push changes
        id: push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if [[ -n "$(git status --porcelain)" ]]; then
            git add .
            git commit -m "chore: Sync extensions ($(date --utc --iso-8601=seconds))"
            git push
            echo "pushed=true" >> $GITHUB_OUTPUT
          else
            echo "pushed=false" >> $GITHUB_OUTPUT
          fi

      - name: Trigger CI workflow
        if: steps.push.outputs.pushed == 'true'
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'ci.yml',
              ref: 'main'
            });
